# Generated by Django 4.1.3 on 2022-12-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('text_data', models.TextField()),
            ],
        ),
    ]
