# Generated by Django 4.1.3 on 2022-12-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomelo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='URL',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='url',
            name='pub_date',
        ),
    ]
